default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost
  username:
  password:

development:
  <<: *default
  database: railsgirls_development

test:
  <<: *default
  database: railsgirls_test

production:
  <<: *default
  database: railsgirls_production
