# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0947099f0842af2623748e8816cd14322f4b06e7bddef4aa0a5bca81c295971054af797386e6e5eadc7e35b520676176ce1a1345da8551ea27326715d7784ac

test:
  secret_key_base: 87c8a6d3a263896d42b5d7d3dfb8fc7426d2b9e20fb4f3b182cd377140fdc1ca907f2f89e7b27c2920d1c0343fb3e4b07f39f979f8ecc298623b5762898ebb63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
