User.create(email: 'admin@example.de', password: 'admin123', password_confirmation: 'admin123')
User.create(email: 'user1@example.de', password: 'test123', password_confirmation: 'test123')
User.create(email: 'user2@example.de', password: 'test123', password_confirmation: 'test123')

Job.create(title: 'Junior Solution Architekt (m/w)',
           description: '<h4>Das erwartet dich bei uns</h4><ul><li>Du bist die Schnittstelle zwischen unseren Mandaten und dem Entwickler Team und verantwortest die Integration neuer Produktanforderungen</li><li>Dabei trägst du die Verantwortung für die Lieferung einzelner (Teil-) Projekte/ Arbeitspakete in Time, Budget und Qualität</li><li>Zu deinen Aufgaben gehören die Konzeption und Architektur der Ad Tech Frameworks und der Monitoring Struktur</li><li>Du entwickelst und betreust die bestehenden Services sowie neue Produkte im Bereich der Online Video Auslieferung und hbbTV</li><li>Die Qualitätssicherung von neuen und bestehenden Technologien und Plattformen gehört ebenso zu deinen Aufgaben sowie die Zusammenarbeit mit externen Dienstleistern</li><li>Du erkennst Zusammenhänge und stellst sicher, dass die inhaltliche Darstellung komplexer Werbeprodukte auf verschiedenen Endgeräten treffsicher und reibungslos abgespielt wird</li><li>Deine agile Denkweise hilft dir, Ergebnisse im Team zu erarbeiten und kreative Lösungen für innovative Problemstellungen zu finden</li></ul><h4>Das bringst du mit</h4><ul><li>Du verfügst über ein erfolgreich abgeschlossenes Studium mit technischem Schwerpunkt oder eine vergleichbare Ausbildung</li><li>Du hast erste Berufserfahrung im technischen Projektmanagement sowie mit dem Einsatz agiler Methoden (Kanban, Scrum)</li><li>Tools &amp; Methoden (zb. Jira) zur Projektplanung, -durchführung und im Projektcontrolling sind dir geläufig</li><li>Du hast Spaß an der Arbeit im Web Development mit Fokus auf JavaScript, CSS und HTML</li><li>Kenntnisse von Methoden, Vorgehensmodellen und deren Anwendung im Software-Entwicklungsprozess (insbesondere in der Sicherstellung von Requirements Engineering und Management)</li><li>Spaß an spannenden Herausforderungen und neuen Technologien bringst du mit</li><li>Sehr gute Deutsch und Englisch Kenntnisse sind für dich selbstverständlich</li></ul><h4>Das bieten wir dir</h4><ul><li>Nutze unser breitgefächertes Angebot an Trainings- und Weiterbildungsmöglichkeiten der ProSiebenSat.1-Academy</li><li>Profitiere von einer flexiblen Arbeitszeitgestaltung mit Home Office und 30 Urlaubstagen pro Jahr</li><li>Arbeite in einem Team, das Millionen begeistert</li><li>Trage mit deinen kompetenten und fernsehbegeisterten Kollegen zum Erfolg von Deutschlands größtem Unternehmen für Werbeforschung und -vermarktung bei</li><li>Sei ein Teil der ProSiebenSat.1 Media SE und freue dich auf eine offene Unternehmenskultur, per „Du" und ohne Dresscode in dem dynamischen Umfeld der Medienbranche</li></ul>')
Job.create(title: 'Werkstudent Online Marketing – eCRM (m/w)',
           description: '<h4>Das bringst du mit</h4><ul><li>Du bist eingeschriebener Student im Bereich BWL, Wirtschaftsinformatik, Marketing, Kommunikation oder in einem vergleichbaren Bereich</li><li>&nbsp;Du hast Spaß am Digital Business sowie eine schnelle Auffassungsgabe und hohe Lernbereitschaft</li><li>Du arbeitest selbstständig und zuverlässig, bist hochmotiviert und hast idealerweise bereits Erfahrungen mit Content Management Tools gesammelt</li><li>&nbsp;Sehr gute Deutschkenntnisse in Wort und Schrift sowie sehr gute MS Office Kenntnisse runden Dein Profil ab</li></ul><h4>Das bieten wir dir</h4><ul><li>Eine ausgesprochen vielseitige und spannende Herausforderung mit viel Gestaltungsspielraum beim Marktführer für Erlebnisse</li><li>Ein wachsendes, innovatives Umfeld mit einer offenen und informellen Unternehmenskultur</li><li>Flexible Arbeitszeiten in der lockeren Umgebung unserer kreativen Büroräume. Und leicht zu erreichen sind wir auch noch: an einem attraktiven Standort nahe des Münchener Werksviertels</li><li>Ein wirklich! besonderes Miteinander: 2x in der Woche können wir uns beim Firmenfitness oder auf dem Volleyballfeld verausgaben, wir laufen gemeinsam beim B2Run und wir sind sehr ambitioniert, beim jährlichen Fußballturnier den ersten Platz zu machen!</li><li>Wir machen nicht nur Erlebnisse – wir (er)leben sie auch: du bekommst eine „Erlebniskarte“ mit einem monatlichen Guthaben für all unsere Erlebnisse</li><li>Wir bieten ein buntes Angebot an Benefits, wie z. B. Mitarbeiterrabatte, vergünstigte Sportangebote und Obst für alle!</li></ul>')
Job.create(title: 'Web Developer (m/w) Video & Creative Solutions',
           description: '<h4>Das erwartet dich bei uns</h4><ul><li>Gestaltung und Entwicklung modernster Web-Portale und interaktiver WebFrontends</li><li>Enge Zusammenarbeit mit Backend-Entwicklern und Ad Management zur Implementierung innovativer UI-Lösungen</li><li>Crossbrowser-Programmierung und -Optimierung</li><li>Identifizierung von Engpässen und Entwicklung von team-orientierten Lösungen</li><li>Perspektivische Leitung eines kleinen agilen Web- und Mobile Teams</li></ul><h4>Das bringst du mit</h4><ul><li>Master-Abschluss in Informatik oder vergleichbare Ausbildung und Berufserfahrung</li><li>Mehrere Jahre Erfahrung in der Softwareentwicklung mit PHP, OOP, Design Patterns, Web-Frameworks und Datenbanken</li><li>Umfassende Kenntnisse in grunt/gulp, jenkins, vagrant, couchbase, HTML5, CSS3, greensock</li><li>Freude an clean code und neuen Technologien sowie Lust wechselnde Design-Frameworks zu nutzen</li><li>Leidenschaft für Best Practice Code, UX/UI und moderne Web-Design-Lösungen</li></ul><h4>Das bieten wir dir</h4><ul><li>Arbeit in einem professionellen und dynamischen Team</li><li>Möglichkeit, eigene Stärken zu entdecken und diese weiter auszubauen</li><li>Hohe Flexibilität und flache Hierarchien bieten Raum für Entwicklung</li><li>Unsere Unternehmenskultur, die fachliches und persönliches Wachstum fördert</li><li>Einen modernen Arbeitsplatz im Herzen von München</li></ul>')
Job.create(title: 'Frontend Developer (m/f)',
           description: '<h4>What you can expect in this role</h4><ul><li>Build reusable, responsive and cross-browser optimized components for our high-performance website</li><li>Participate in the process from ideation, user testing and design to development</li><li>Work close with the designer and the other developers on new features</li><li>Run AB tests and evaluate the impact of your work in terms of our KPIs</li><li>Explain technical concepts to non-technical colleagues</li></ul><h4>Your essential experience and education</h4><ul><li>You love responsive design and have experience in the areas of semantic HTML, scalable CSS and Javascript</li><li>You have a background in computer science either from a bachelor\'s degree program and/or work experience</li><li>You have proficient English skills and are able to communicate honestly and openly with your colleagues</li><li>You are a motivated, compassionate individual who enjoys collaboration and is eager to learn from and teach others</li><li>Experience with Java and server-side development is a plus but not a must</li></ul><h4>What\'s in it for you?</h4><ul><li>Hands-on work after quick ramp up &amp; openness to new solutions and improvements</li><li>We’ll give you a personal development budget, to go to conferences, buy books and grow with us</li><li>Stylight is #1 Meetup organizer in Munich, and deeply involved in the local tech community</li><li>International and diverse workplace: 44% non-German and 65% female</li><li>We have one of the best office spaces in Munich (and actually in Germany)</li></ul>')
Job.create(title: 'Praktikant (m/w) Business Intelligence',
           description: '<h4>Das erwartet dich bei uns</h4><ul><li>Selbstständige Erstellung von Ad Hoc Auswertungen und Reports mit Performance-Kennzahlen aller digitalen Kanäle (Webseiten, Mobile-Apps, HbbTV &amp; SmartTV)</li><li>Maßnahmen zur Sicherung der Datenqualität</li><li>Datenvisualisierung mittels Erstellung von Charts und Dashboards</li><li>Zusammenarbeit mit Fachabteilungen und externen Dienstleistern</li></ul><h4>Das bringst du mit</h4><ul><li>Studium im Bereich Naturwissenschaften, Informatik, Wirtschaftsinformatik oder Studiengänge mit statistischen Schwerpunkt</li><li>Eigenständige, zuverlässige und ergebnisorientierte Arbeitsweise</li><li>Lernbereitschaft rund um Datenbanktechnologien und BI Tools</li><li>Gute Kenntnisse im Umgang mit MS Excel und MS PowerPoint</li></ul><h4>Das bieten wir dir</h4><ul><li>Erhalte Einblicke in unsere Geschäftsbereiche und erweitere in eigenständigen Projekten deine Fachkompetenz, um dich auf deinen Berufseinstieg vorzubereiten</li><li>Freue dich auf eine offene Unternehmenskultur, per „Du" und ohne Dresscode im dynamischen Umfeld der Medienbranche</li><li>Arbeite an modern ausgestatten Arbeitsplätzen und nutze unser großes Sportangebot (u. a. Yoga, Fußball oder Workouts), Post-, Wäsche- und Bügelservice sowie viele Cafés und WLAN auf dem Campus</li></ul>')

(1..13).each do |index|
  current_idea = Idea.create!(name: "Idea #{index}", description: 'At vero eos et accusam et justo duo dolores et ea rebum.')
  current_idea.picture = Rails.root.join("app/assets/images/ideas/idea#{index}.jpg").open
  current_idea.save!
  current_idea.comments.create(user_name: 'user1', body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.')
end